/* DO NOT EDIT, file generated by nestjs-i18n */
  
/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "main": {
        "notification": {
            "newMatch": {
                "title": string;
                "body": string;
            };
        };
        "email": {
            "request-account-deletion": {
                "subject": string;
                "hello": string;
                "warning": string;
                "receivedRequest": string;
                "proceedInstructions": string;
                "deleteButton": string;
                "expirationNote": string;
                "warningMessage": string;
                "feedbackRequest": string;
                "securityWarning": string;
                "footer": string;
            };
            "verification-successful": {
                "subject": string;
                "title": string;
                "header": string;
                "greeting": string;
                "verificationSuccess": string;
                "nextSteps": string;
                "disclaimer": string;
                "footer": string;
            };
            "email-verification": {
                "subject": string;
                "title": string;
                "header": string;
                "greeting": string;
                "thankYou": string;
                "instructions": string;
                "disclaimer": string;
                "footer": string;
            };
            "request-password-reset": {
                "subject": string;
                "title": string;
                "greeting": string;
                "receivedRequest": string;
                "instructions": string;
                "expirationNote": string;
                "ignoreMessage": string;
                "securityNote": string;
                "contactSupport": string;
                "footer": string;
            };
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
