import { Language } from "./translate.service";

export const de: Language = {
    bgLocationServiceTitle: "Real Life Dating EIN",
    bgLocationServiceBody: "Bereit dich zu beeindrucken..",
    createAccount: "Registrieren",
    signIn: "Anmelden",
    invalidCredentials: "E-Mail oder Passwort falsch.",
    signingIn: "Einen Moment..",
    contactSupport: "Funktioniert etwas nicht?",
    gettingReadyToAmazeYou: "Bereit, dich zu beeindrucken..",
    datingAppsAreBroken: "Dating apps are Broken",
    stopSwipingMeetIrl: "Stop Swiping. Meet IRL.",
    verificationCodeResend: "Neuer Code",
    verificationCodeInvalid: "Ungültiger Verifizierungscode",
    invalidEmailOrExists: "Email ungültig oder existiert bereits.",
    invalidEmail: "Email ungültig.",
    termsDisclaimer: {
        p1: "Durch Tippen auf 'Konto erstellen' oder 'Anmelden' stimmst du unseren ",
        terms: "AGBs",
        p2: " zu. Unsere ",
        privacyCookie: "Datenschutz- und Cookie-Richtlinie.",
    },
    yourEmail: "Deine E-Mail",
    email: "E-Mail",
    yourPassword: "Dein Passwort",
    resetPassword: "Passwort zurücksetzen",
    passwordForgotten: "Passwort vergessen?",
    password: "Passwort",
    houseRules: {
        mainTitle: "Hausregeln",
        titleRespectful: "Sei Respektvoll.",
        descrRespectful:
            "Wir haben eine 0-Toleranz-Politik gegenüber respektlosem Verhalten.",
        titleAcceptNo: "Akzeptiere ein Nein.",
        descrAcceptNo:
            "Sei nicht aufdringlich. Wenn es nicht passt, akzeptiere es.",
        titleAuthentic: "Bleib Authentisch.",
        descrAuthentic: "Sei du selbst. Vertrau uns, es funktioniert.",
        titleWaitWeird: "Nicht warten. Mach's nicht komisch.",
        descrWaitWeird:
            "Sprich gleich an. Beobachte nicht. Sei einfach lässig und höflich.",
        titleDontRush: "Nicht hetzen.",
        descrDontRush:
            "Versuche nicht, „abzuschließen“. Habe eine gute Zeit, der Rest passiert von selbst.",
    },
    iUnderstand: "Verstanden",
    violatingRules: {
        p1: "Das Verletzen dieser Regeln sperrt dich für mindestens ",
        duration: "12 Monate",
        p2: ". Keine Ausnahmen.",
    },
    noAccessToMediaLib: "Kein Zugriff auf die Mediathek.",
    addPhotos: "Fotos hinzufügen",
    clickToUploadImages: "Klicken, um Bilder hochzuladen.",
    continue: "Weiter",
    iWantTo: "Ich möchte",
    approach: "Ansprechen",
    beApproached: "Angesprochen werden",
    approachDescr:
        "Du ergreifst die Initiative und sprichst im echten Leben an.",
    beApproachedDescr: "Werde angesprochen. Sicher und respektvoll.",
    both: "Beides",
    bothDescr: "Sprich an und werde angesprochen.",
    changePossible: "Du kannst diese Einstellung später nicht ändern.",
    approachMeBetween: "Sprich mich an..",
    approachMeBetweenDescr:
        "Zu welchen Zeiten fühlst du dich wohl, angesprochen zu werden? Standard ist tagsüber.",
    from: "Von",
    until: "Bis",
    fromDescr: "Sprich mich an, von",
    untilDescr: "bis",
    letThemKnow: "Lass sie wissen",
    messageShownToPersonApproaching:
        "Die Nachricht wird der Person angezeigt, die dich ansprechen möchte.",
    done: "Fertig",
    registering: "Erstelle Account..",
    noPickUpLinesBeChill: "Keine Anmachsprüche bitte. Sei einfach lustig.",
    findWithSpace: "Finde ",
    myBirthDayIs: "Mein Geburtstag ist",
    yourAgeWillBePublic: "Dein Alter ist öffentlich",
    bookSafetyCall: "Sicherheitsanruf buchen",
    retainRightToRejectApplicants:
        "Wir behalten uns das Recht vor, Bewerber abzulehnen, um sicherzustellen, dass sich jeder sicher und respektiert fühlt.",
    callBookedBtnLbl: "Ich werde da sein",
    verificationCallQuestions: "Was wir dich fragen",
    verificationNeeded: "Wir brauchen deine Verifizierung",
    permissionToLocationDenied:
        "Zugriff auf den Standort wurde verweigert. Ohne deinen Standort wirst du weder angesprochen, noch kannst du jemanden via Offlinery ansprechen.",
    dontApproachHere: "Hier nicht ansprechen",
    whatAreSpotsToNotApproachYou:
        "An welchen Orten möchtest du nicht angesprochen werden? Dein Fitnessstudio, Arbeitsplatz?",
    youAreUndercover: "Du bist undercover",
    nobodyWillSeeYou: "Niemand wird dich hier sehen.",
    myLocation: "Mein Standort",
    youAreHere: "Du bist hier.",
    longPressMapSafeZoneInstruction:
        "Lange tippen, um eine Sicherheitszone hinzuzufügen. Tippe auf eine Region, um deinen Radius anzupassen.",
    adjustRegionRadius: "Regionradius anpassen",
    whatIsYourEmail: "Was ist deine E-Mail?",
    whatIsYourEmailDescr:
        "Verliere keinen Zugriff auf dein Konto, verifiziere deine E-Mail.",
    wantToReceiveNews:
        "Ich möchte Nachrichten, Updates und Angebote von Offlinery erhalten.",
    enterVerificationCode: "E-Mail Verifizierung",
    verificationCodeLoadingBtnLbl: "Sende E-Mail..",
    verify: "Bestätigen",
    verificationCodeSent:
        "Der 6-stellige Code, den wir dir per E-Mail gesendet haben",
    myFirstNameIs: "Mein Vorname ist",
    myFirstNameDescr: "So wirst du in Offlinery angezeigt.",
    enterFirstName: "Vornamen eingeben",
    woman: "Frau",
    women: "Frauen",
    man: "Mann",
    men: "Männer",
    more: "Mehr",
    iAmA: "Ich bin ein(e)",
    casual: "Casual",
    friendship: "Freundschaft",
    relationship: "Beziehung",
    iWantA: "Ich will eine",
    genderMoreComingSoon: "Diese Option kommt so schnell wie möglich!",
    ageRange: "Altersgruppe",
    genderLookingForAlertTitle: "Datenschutz",
    genderLookingForAlertDescr:
        "Diese Information is notwendig, um dir grundlegende Funktionalitäten bereitzustellen. Mit dem Akzeptieren bestätigst du damit einverstanden zu sein.",
    decline: "Ablehnen",
    accept: "Akzeptieren",
    dataPrivacy: "Data Privacy",
    iLookFor: "Ich suche",
    pwdErrSecurityGuideline:
        "Das Passwort muss mindestens 1 Zahl, 1 Groß- und 1 Kleinbuchstaben enthalten und zwischen 6-40 Zeichen lang sein.",
    pwdErrNotMatching: "Passwörter stimmen nicht überein.",
    setStrongPassword: "Starkes Passwort festlegen",
    changePassword: "Passwort ändern",
    save: "Speichern",
    updating: "Speichere..",
    oldPasswordInvalid: "Altes Passwort ungültig",
    enterOldPassword: "Altes Passwort eingeben",
    currentPassword: "Aktuelles Passwort",
    enterPassword: "Passwort eingeben",
    strongPassword: "Starkes Passwort",
    newPassword: "Neues Passwort",
    repeatPassword: "Passwort wiederholen",
    safetyCheck: "Sicherheitscheck",
    safetyCheckDescr:
        "Notwendig, damit sich Angesprochene zu jeder Zeit sicher und wohl fühlen",
    book15MinCall: "Anruf buchen",
    book15MinCallDescr: "Ein 15-minütiger Verifizierungsanruf.",
    iPreferKYC: "KYC starten",
    iPreferKYCDescr: "Reguliertes 3rd-Party-KYC (noch nicht verfügbar).",
    verificationInProgress: "Verifizierung läuft",
    verificationSuccessful: "Verifiziert!",
    bookNewCall: "Neuen Anruf buchen",
    pleaseDoNotMakeDoubleBookings: "Bitte keine Doppelbuchungen vornehmen.",
    switchToBeApproached: `Wechsel zu "Angesprochen werden"`,
    whySwitchToBeApproached: `Wenn du zu "Angesprochen werden" wechselst, wird keine Verifizierung benötigt und du kannst sofort loslegen. Du kannst trotzdem am Sicherheitsanruf teilnehmen, um verifiziert zu werden.`,
    somethingWrongQ: "Irgendwas schief gelaufen?",
    peopleYouMightHaveMet:
        "Menschen, die du vielleicht getroffen hast. Bewerte sie, melde sie oder bleibe in Kontakt.",
    weMetFrom: "Wir haben uns getroffen von",
    toThisDate: "bis zu diesem Datum",
    beNearTheseHotspotsToMeet:
        "In der Nähe dieser Hotspots zu sein erhöht deine Chancen, deine bessere Hälfte zu treffen.",
    wasSeenNear: "nahe", // OF-233 adapt to geofencing
    reportPerson: "Person melden",
    meetIRL: "Im echten Leben treffen",
    profileView: "Profilansicht",
    noUserIdAssignedCannotListenToNotifications:
        "Kein Benutzer-ID zugewiesen! Kann keine Benachrichtigungen empfangen!",
    couldNotFetchNotificationToken:
        "Benachrichtigungstoken konnte nicht abgerufen werden",
    findPeople: "Finden",
    encounters: "Begegnungen",
    settings: "Einstellungen",
    destination: "Ziel",
    navigateTo: "Navigiere zu ",
    yourLocation: "Dein Standort",
    calculating: "Berechne..",
    changePreferencesDescr:
        "Ändere deine Einstellungen oder aktualisiere dein Profil.",
    nonNegotiable: "Must Have's",
    bio: "Bio",
    defaultBio: "Bitte keine Pick-Up Lines. Ein nettes Hallo reicht völlig.",
    bioTooltip: "Dies wird anderen Nutzern beim Ansprechen angezeigt.",
    updateImages: "Bilder updaten",
    updateSafeZones: "Safe Zones updaten",
    errNoUserProvided: "Fehler: Kein Nutzer angegeben",
    reportIncident: {
        disrespectful: "Respektlos",
        sexualHarassment: "Sexuelle Belästigung",
        violentBehavior: "Gewalttätiges Verhalten",
        other: "Andere",
    },
    onlyReportThatWasDisrespectful:
        "Bitte melde nur Personen, die respektlos waren, ein Nein nicht akzeptiert haben oder sich auf andere Weise unangemessen verhalten haben.",
    typeOfIncident: "Art des Vorfalls",
    selectIncidentType: "Vorfallstyp auswählen",
    search: "Suchen..",
    describeIncident: "Beschreibe den Vorfall / Fehlverhalten",
    keepMeInTheLoopEmail: "Bitte halte mich per E-Mail auf dem Laufenden.",
    reportNow: "Jetzt melden",
    calendlySchedulingPageDefault: "Calendly Terminseite",
    encounterInterest: {
        notMet: "Nicht getroffen",
        metNotInterested: "Getroffen, nicht interessiert",
        metInterested: "Getroffen, interessiert",
    },
    ratingDescr:
        "Je höher, desto vertrauenswürdiger ist die Person (5 = am besten).",
    trust: "Vertrauen",
    report: "Melden",
    reported: "Gemeldet..",
    navigate: "Navigieren",
    permissionToBackgroundLocationDenied: `Zugriff auf den Standort im Hintergrund wurde verweigert. Ohne deinen Standort wirst du weder angesprochen, noch kannst du jemanden via Offlinery ansprechen. Bitte stelle den Standortzugriff auf "Immer" in den Einstellungen ein.`,
    youAreLive: "Du bist live!",
    ghostModeDescr:
        "Geistmodus. Niemand wird dich sehen! Drücke den Schalter oben, um live zu gehen.",
    errRequestingPermissions:
        "Ein Fehler ist bei der Anforderung der Berechtigungen aufgetreten.",
    youAreLiveApproachDescr:
        "Du erhältst Benachrichtigungen, wenn jemand Interessantes in der Nähe ist!",
    youAreLiveBeApproachedDescr:
        "Personen, die dich interessant finden könnten, erhalten Benachrichtigungen, wenn du in der Nähe bist!",
    live: "Live",
    ghostMode: "Geistmodus",
    saving: "Speichern..",
    enterMessage: "Nachricht oder Kontaktdetails eingeben..",
    sendMessage: "Senden",
    receivedMessage: "Letzte Nachricht",
    leaveMessage: "Nachricht schreiben",
    leaveMessageBtnLbl: "Kontakt",
    messageInstructions:
        "Falls nicht bereits in Person geschehen, dann füge deine Kontaktdetails hinzu.",
    messageWarning: "Es wird nur die letzte Nachricht gespeichert.",
    messageUnableToSend: "Nachricht kann nicht gesendet werden.",
    dangerZone: "Gefahren-Zone",
    logout: "Logout",
    deleteAccount: "Account löschen",
    deletionRequested: "Löschung beantragt",
    accountDeletionRequestedAlert:
        "Wir haben dir eine E-Mail geschickt. Klick auf den Link, um deinen Account unwiderruflich zu löschen.",
    justNow: "gerade eben",
    minutesAgo: "Minute(n) her",
    hoursAgo: "Stunde(n) her",
    daysAgo: "Tag(e) her",
    weeksAgo: "Woche(n) her",
    monthsAgo: "Monat(e) her",
    yearsAgo: "Jahr(e) her",
    appIntroductionSkip: "Überspringen",
    appIntroductionBack: "Zurück",
    appIntroductionNext: "Weiter",
    appIntroductionGetStarted: "Loslegen",
    page1Title: "Triff dich im echten Leben",
    page1Description:
        "Alles passiert <b>offline</b>. Es gibt keine langen Chats und kein Swipen.",
    page1Conclusion:
        "<b>Werde angesprochen</b> oder <b>sprich an</b> so wie vor Dating Apps.",
    page2Title: "Auf sichere Weise",
    page2Description:
        "Ansprechende werden von uns in einem <b>persönlichen Verifizierungsanruf</b> auf ihre Vertrauenswürdigkeit überprüft.",
    page2Conclusion: "Wir haben <b>0 Toleranz</b> für respektloses Verhalten.",
    page3Title: "Eine Bitte",
    page3Description:
        "Damit die App funktioniert muss Offlinery <b>immer</b> wissen wo du bist. Du kannst das Tracking <b>jederzeit pausieren</b> und festlegen, wann und wie du Leute treffen möchtest.",
    page3Conclusion:
        "Klicke auf '<b>immer erlauben</b>' wenn dich Offlinery nach deinem Standort fragt.",
    page4Title: "Daten & Sicherheit",
    page4Description:
        "Diese App ist <b>DSGVO-konform</b>. Offlinery wurde von Grund auf so konzipiert, dass sich jeder <b>wohl fühlt</b>.",
    page4Conclusion:
        "Diese App funktioniert nur, wenn du dich zu <b>jederzeit sicher fühlst</b>.",
    letsMeetIRL: "In echt treffen",
    dropdownSelectChoicePlaceholder: "Bitte wähle",
    userLocationWasUpdatedLastTime: "Zuletzt hier gesehen: ",
    fieldRequired: "Dieses Feld wird benötigt",
    inputInvalid: "Eingabe ist ungültig",
    cancel: "Abbrechen",
    goToSettings: "Gehe zu Einstellungen",
    permissionRequired: "Zugriff auf Gallerie benötigt",
    pleaseChangePermission:
        "Bitte ändere die Zugriffsrechte auf deine Bilder um fortzufahren.",
};
