// @dev Other languages have to be typed as Language!
export const en = {
    createAccount: "Create Account",
    signIn: "Sign in",
    invalidCredentials: "Email or password invalid.",
    signingIn: "Signing in..",
    troubleSignIn: "Trouble signing in?",
    gettingReadyToAmazeYou: "Getting ready to amaze you..",
    datingAppsAreBroken: "Dating apps are Broken",
    stopSwipingMeetIrl: "Stop Swiping. Meet IRL.",
    termsDisclaimer: {
        p1: "By tapping 'Create account' or 'Sign in', you agree to our ",
        terms: "Terms",
        p2: ". See how we process your data in our ",
        privacyCookie: "Privacy and Cookie Policy.",
    },
    yourEmail: "Your email",
    email: "Email",
    yourPassword: "Your password",
    password: "Password",
    houseRules: {
        mainTitle: "House rules",
        titleRespectful: "Be Respectful.",
        descrRespectful: "We've a 0 tolerance for disrespectful behavior.",
        titleAcceptNo: "Accept a No.",
        descrAcceptNo: "Don't be pushy. If there is no vibe, accept it.",
        titleAuthentic: "Be authentic.",
        descrAuthentic: "Be yourself. Trust us, it works.",
        titleWaitWeird: "Don't wait. Don't make it weird.",
        descrWaitWeird:
            "Approach immediately. Don't observe and watch. Just be casual and polite.",
        titleDontRush: "Don't rush it.",
        descrDontRush:
            "Don't try to 'close'. Have a good time, the rest follows naturally.",
    },
    iUnderstand: "I understand",
    violatingRules: {
        p1: "Violating these rules blocks you from using this app for at least ",
        duration: "12 months",
        p2: ". We have no mercy.",
    },
    noAccessToMediaLib: "No access to media library.",
    addPhotos: "Add photos",
    clickToUploadImages: "Click to upload images.",
    continue: "Continue",
    iWantTo: "I want to",
    approach: "Approach someone",
    beApproached: "Be approached",
    approachDescr:
        "Approach people you are interested in. Meet them in-real-life where they are.",
    beApproachedDescr:
        "Be approached by people you are interested in. Safely and Respectfully.",
    both: "Both",
    bothDescr: "Want to approach and be approached by people you like?",
    changePossible: "You can't change this later.",
    approachMeBetween: "Approach me between",
    approachMeBetweenDescr:
        "What are times you feel comfortable being approached at? Default is during the day.",
    from: "From",
    until: "Until",
    fromDescr: "Approach me starting from",
    untilDescr: "Approach me until",
    letThemKnow: "Let them know",
    messageShownToPersonApproaching:
        "The message is shown to the person approaching you before.",
    done: "Done",
    registering: "Registering..",
    noPickUpLinesBeChill: "No pick-up lines please. Just be chill.",
    findWithSpace: "Find ",
    myBirthDayIs: "My birthday is",
    yourAgeWillBePublic: "Your age will be public",
    bookSafetyCall: "Book Safety Call",
    retainRightToRejectApplicants:
        "We retain our right to reject applicants to ensure everyone feels safe and respected.",
    callBookedBtnLbl: "I'll take the call",
    permissionToLocationDenied: "Permission to access location was denied.",
    dontApproachHere: "Don't approach me here",
    whatAreSpotsToNotApproachYou:
        "What are spots you don't want to be approached at? Your gym, workplace?",
    youAreUndercover: "You're undercover",
    nobodyWillSeeYou: "Nobody will see you here.",
    myLocation: "My Location",
    youAreHere: "You are here.",
    longPressMapSafeZoneInstruction:
        "Long press on the map to add a circular region. Tap a region to select it and adjust its radius.",
    adjustRegionRadius: "Adjust Region Radius",
    whatIsYourEmail: "What's your email?",
    whatIsYourEmailDescr:
        "Don't lose access to your account, verify your email.",
    wantToReceiveNews:
        "I want to receive news, updates and offers from Offlinery.",
    enterVerificationCode: "Enter Verification Code",
    verificationCodeLoadingBtnLbl: "Sending email..",
    verify: "Verify",
    verificationCodeSent: "The 6-digit code we sent you per email",
    verificationCodeResend: "Resend Code",
    verificationCodeInvalid: "Invalid Verification Code",
    invalidEmailOrExists: "Email is either invalid or already exists.",
    invalidEmail: "Email invalid.",
    myFirstNameIs: "My first name is",
    myFirstNameDescr: "This is how you will appear in Offlinery.",
    enterFirstName: "Enter first name",
    woman: "Woman",
    women: "Women",
    man: "Man",
    men: "Men",
    more: "More",
    iAmA: "I am a",
    genderMoreComingSoon:
        "We will be adding this option as soon as possible. You will have the option later on to change this to something you truly identify with.",
    iLookFor: "I look for",
    pwdErrSecurityGuideline:
        "Password must contain at least 1 number, 1 big and small letter and have between 6-40 characters.",
    pwdErrNotMatching: "Passwords do not match.",
    setStrongPassword: "Set a strong password",
    changePassword: "Change password",
    save: "Save",
    updating: "Updating..",
    oldPasswordInvalid: "Old password invalid",
    enterOldPassword: "Enter old password",
    currentPassword: "Current password",
    enterPassword: "Enter password",
    strongPassword: "Strong password",
    newPassword: "New password",
    repeatPassword: "Repeat password",
    safetyCheck: "Safety Check",
    safetyCheckDescr:
        "Everyone should have a great experience and feel safe at all times.",
    book15MinCall: "Book call",
    book15MinCallDescr: "15 minute verification call.",
    iPreferKYC: "Start KYC",
    iPreferKYCDescr: "Regulated 3rd party KYC (coming soon).",
    verificationInProgress: "Verification in progress..",
    verificationSuccessful: "You got approved!",
    bookNewCall: "Book new call",
    pleaseDoNotMakeDoubleBookings: "Please do not make double bookings.",
    somethingWrongQ: "Something wrong?",
    peopleYouMightHaveMet:
        "People you might have met. Rate them, Report them or stay in touch.",
    weMetFrom: "We met from",
    toThisDate: "to this date",
    beNearTheseHotspotsToMeet:
        "Being near these hotspots increases your odds of meeting your soulmate.",
    reportPerson: "Report person",
    meetIRL: "Meet in IRL",
    profileView: "Profile view",
    noUserIdAssignedCannotListenToNotifications:
        "No user ID assigned! Cannot listen to notifications!",
    couldNotFetchNotificationToken: "Could not fetch notification token",
    findPeople: "Find people",
    encounters: "Encounters",
    settings: "Settings",
    destination: "Destination",
    navigateTo: "Navigate to ",
    yourLocation: "Your location",
    calculating: "Calculating..",
    changePreferencesDescr: "Change your preferences or update your profile.",
    bio: "Bio",
    updateImages: "Update images",
    updateSafeZones: "Update Safe Zones",
    errNoUserProvided: "Error: No user provided",
    reportIncident: {
        disrespectful: "Disrespectful",
        sexualHarassment: "Sexual harassment",
        violentBehavior: "Violent behavior",
        other: "Other",
    },
    onlyReportThatWasDisrespectful:
        "Please only report people that were disrespectful, didn't accept a No or even did misbehave in a different way.",
    typeOfIncident: "Type of Incident",
    selectIncidentType: "Select incident type",
    search: "Search..",
    describeIncident: "Describe the incident / misbehavior",
    keepMeInTheLoopEmail: "Please keep me in the loop via email.",
    reportNow: "Report now",
    calendlySchedulingPageDefault: "Calendly Scheduling Page",
    encounterInterest: {
        notMet: "Not met",
        metNotInterested: "Met, not interested",
        metInterested: "Met, interested",
    },
    ratingDescr: "The higher the more trustworthy the person is (5 = best).",
    trust: "Trust",
    report: "Report",
    reported: "Reported..",
    navigate: "Navigate",
    permissionToBackgroundLocationDenied:
        "Permission to access location in background was denied.",
    youAreLive: "You are live!",
    ghostModeDescr:
        "Ghost mode. Nobody will see you! Press the toggle on the top to go live.",
    errRequestingPermissions: "An error occurred while requesting permissions.",
    youAreLiveApproachDescr:
        "You will receive notifications when someone interesting is nearby!",
    youAreLiveBeApproachedDescr:
        "People you may find interesting will receive notifications when you are nearby!",
    live: "Live",
    ghostMode: "Ghost Mode",
    saving: "Saving..",
    enterMessage: "Enter message or contact details..",
    sendMessage: "Send message",
    receivedMessage: "Received message",
    leaveMessage: "Leave message",
    leaveMessageBtnLbl: "Contact",
    messageInstructions:
        "You might want to add your contact details, if you didn't share them in person already.",
    messageWarning: "Only the last message will be saved.",
    dangerZone: "Danger Zone",
    logout: "Logout",
    deleteAccount: "Delete account",
    deletionRequested: "Deletion requested",
    accountDeletionRequestedAlert:
        "We've sent you a link to your email. Click on the link to irrevocably delete your account.",
};
