// @dev Other languages have to be typed as Language!
export const en = {
    createAccount: 'Create Account',
    signIn: 'Sign in',
    signingIn: 'Signing in..',
    troubleSignIn: 'Trouble signing in?',
    gettingReadyToAmazeYou: 'Getting ready to amaze you..',
    datingAppsAreBroken: 'Dating apps are Broken',
    stopSwipingMeetIrl: 'Stop Swiping. Meet IRL.',
    termsDisclaimer: {
        p1: 'By tapping “Create account” or “Sign in”, you agree to our ',
        terms: 'Terms',
        p2: '. See how we process your data in our ',
        privacyCookie: 'Privacy and Cookie Policy.',
    },
    yourEmail: 'Your email',
    email: 'Email',
    yourPassword: 'Your password',
    password: 'Password',
    houseRules: {
        titleRespectful: 'Be Respectful.',
        descrRespectful: 'We\'ve a 0 tolerance for disrespectful behavior.',
        titleAcceptNo: 'Accept a No.',
        descrAcceptNo: 'Don\'t be pushy. If there is no vibe, accept it.',
        titleAuthentic: 'Be authentic.',
        descrAuthentic: 'Be yourself. Trust us, it works.',
        titleWaitWeird: 'Don\'t wait. Don\'t make it weird.',
        descrWaitWeird: 'Approach immediately. Don\'t observe and watch. Just be casual and polite.',
        titleDontRush: 'Don\'t rush it.',
        descrDontRush: 'Don\'t try to \'close\'. Have a good time, the rest follows naturally.',
    },
    iUnderstand: 'I understand',
    violatingRules: {
        p1: 'Violating these rules blocks you from using this app for at least ',
        duration: '12 months',
        p2: '. We have no mercy.'
    },
    noAccessToMediaLib: 'No access to media library.',
    addPhotos: 'Add photos',
    clickToUploadImages: 'Click to upload images.',
    continue: 'Continue',
    iWantTo: 'I want to',
    approach: 'Approach',
    beApproached: 'Be approached',
    approachDescr: 'Approach people you are interested in. Meet them in-real-life where they are.',
    beApproachedDescr: 'Be approached by people you are interested in. Safely and Respectfully.',
    both: 'Both',
    bothDescr: 'Want to approach and be approached by people you like? (not yet supported)',
    approachMeBetween: 'Approach me between',
    approachMeBetweenDescr: 'What are times you feel comfortable being approached at? Default is during the day.',
    from: 'From',
    until: 'Until',
    fromDescr: 'Approach me starting from',
    untilDescr: 'Approach me until',
    letThemKnow: 'Let them know',
    messageShownToPersonApproaching: 'The message is shown to the person approaching you before.',
    done: 'Done',
    registering: 'Registering..',
    noPickUpLinesBeChill: 'No pick-up lines please. Just be chill.',
    findWithSpace: 'Find ',
    myBirthDayIs: 'My birthday is',
    yourAgeWillBePublic: 'Your age will be public',
    bookSafetyCall: 'Book Safety Call',
    retainRightToRejectApplicants: 'We retain our right to reject applicants to ensure everyone feels safe and respected.',
    callBookedQuestion: 'Call booked?',
    permissionToLocationDenied: 'Permission to access location was denied.',
    dontApproachHere: 'Don\'t approach me here',
    whatAreSpotsToNotApproachYou: 'What are spots you don\'t want to be approached at? Your gym, workplace?',
    youAreUndercover: 'You\'re undercover',
    nobodyWillSeeYou: 'Nobody will see you here.',
    myLocation: 'My Location',
    youAreHere: 'You are here.',
    longPressMapSafeZoneInstruction: 'Long press on the map to add a circular region. Tap a region to select it and adjust its radius.',
    adjustRegionRadius: 'Adjust Region Radius',
    whatIsYourEmail: 'What\'s your email?',
    whatIsYourEmailDescr: 'Don\'t lose access to your account, verify your email.',
    wantToReceiveNews: 'I want to receive news, updates and offers from Offlinery.',
    myFirstNameIs: 'my first name is',
    myFirstNameDescr: 'This is how you will appear in Offlinery.',
    enterFirstName: 'Enter first name',
    woman: 'Woman',
    women: 'Women',
    man: 'Man',
    men: 'Men',
    more: 'More',
    iAmA: 'I am a',
    genderMoreComingSoon: 'We will be adding this option as soon as possible. You will have the option later on to change this to something you truly identify with.',
    iLookFor: 'I look for',
    pwdErrSecurityGuideline: 'Password must contain at least 1 number, 1 big and small letter and have between 6-40 characters.',
    pwdErrNotMatching: 'Passwords do not match.',
    setStrongPassword: 'Set a strong password',
    changePassword: 'Change password',
    setPassword: 'Set password',
    save: 'Save',
    enterOldPassword: 'Enter old password',
    currentPassword: 'Current password',
    enterPassword: 'Enter password',
    strongPassword: 'Strong password',
    newPassword: 'New password',
    repeatPassword: 'Repeat password',
    safetyCheck: 'Safety Check',
    safetyCheckDescr: 'This will only work if everyone has a great experience and feels safe at all times.',
    book15MinCall: 'Book a 15 Minute call',
    book15MinCallDescr: 'This will be a Video call. Making sure you have good intentions using this app.',
    iPreferKYC: 'I prefer to KYC',
    iPreferKYCDescr: 'Alternatively, you can do a regulated 3rd party KYC. You\'ll be charged the provider\'s fee since we incur real costs (coming soon).',
    verificationInProgress: 'Verification in progress..',
    bookNewCall: 'Book new call',
    pleaseDoNotMakeDoubleBookings: 'Please do not make double bookings.',
    somethingWrongQ: 'Something wrong?',
}