export const ROUTES = {
    Welcome: "Welcome" as const,
    HouseRules: "HouseRules" as const,
    /** @dev MainTabView then manages the tab routes */
    MainTabView: "Main_TabView" as const,
    Login: "Login" as const,
    ResetPassword: "ResetPassword" as const,
    Main: {
        Encounters: "Main_Encounters" as const,
        ReportEncounter: "Main_ReportEncounter" as const,
        FindPeople: "Main_FindPeople" as const,
        ProfileSettings: "Main_ProfileSettings" as const,
        NavigateToApproach: "Main_NavigateToApproach" as const,
        ProfileView: "Main_ProfileView" as const,
    },
    Onboarding: {
        Email: "Onboarding_Email" as const,
        VerifyEmail: "Onboarding_VerifyEmail" as const,
        Password: "Onboarding_Password" as const,
        FirstName: "Onboarding_Firstname" as const,
        BirthDay: "Onboarding_Birthday" as const,
        GenderChoice: "Onboarding_GenderChoice" as const,
        GenderLookingFor: "Onboarding_GenderLookingFor" as const,
        IntentionsChoice: "Onboarding_IntentionsChoice" as const,
        ApproachChoice: "Onboarding_ApproachChoice" as const,
        SafetyCheck: "Onboarding_SafetyCheck" as const,
        BookSafetyCall: "Onboarding_BookSafetyCall" as const,
        AddPhotos: "Onboarding_AddPhotos" as const,
        WaitingVerification: "Onboarding_WaitingVerification" as const,
        // user should just blacklist their home for now if they want to, ILiveHere: 'Onboarding_ILiveHere',
        DontApproachMeHere: "Onboarding_DontApproachMeHere" as const,
        ApproachMeBetween: "Onboarding_ApproachMeBetween" as const,
        BioLetThemKnow: "Onboarding_BioLetThemKnow" as const,
        AppIntroductionSlider: "Onboarding_AppIntroductionSlider" as const,
    },
};
